### ISSUE TITLE
Problème d'installation

### ISSUE THREAD

**Issue by Backins** [benKazmierczak/testUnitaire#1]
Liste : 
* dossier config nécessaire sur git. Sans ça impossible de clone et installer ce repo
* .env manquant, il est important d'avoir ce .env (le faire manuellement sans une copie c'est chiant :p 
* Ensuite, deux problèmes : 
1. Dans ton fichier Util/Product.php il manque le namespace : `namespace App\Util;`
2. Idem dans le fichier User.php du même dossier. 

Je te laisse fixe le problème, si tu as des questions dit moi :)

**Comment by benKazmierczak** [comment]
Problème fix
